### ISSUE TITLE
Framework가 안뜨네요;;

### ISSUE THREAD

**Issue by fora22** [GKO95/FlowDebugger#1]
![UWP_Error](https://user-images.githubusercontent.com/48875566/93659635-3fb8f580-fa82-11ea-899f-7460a4b4c50d.png)

uwp app모습이 안보이네요;; (화질 구린건 죄송...지금 설치중이라 VS를 못열어요;;)
visual studio installer에서 설치한게 달라서 그런가 싶은데 형 visual studio 어떤거 깔려있는지 알 수 있습니까?
지금 저는 4개 정도 깔려있는데요 @GKO95 

- .Net desktop development
- Desktop development with C++
- Universal Windows Platform development
- Python development

**Comment by GKO95** [comment]
![image](https://user-images.githubusercontent.com/44629526/93659731-60ce1600-fa83-11ea-9e03-e71988c389b6.png)
VS2019 Commuinty 에디션 사용 중. Universal Windows Platform 설치가 가장 중요.

스크린샷은 Window + Shift + S 누르면 쉽게 찍을 수 있다.

**Comment by fora22** [comment]
<img width="995" alt="uwp_error" src="https://user-images.githubusercontent.com/48875566/93659794-2d3fbb80-fa84-11ea-8495-e2774b4d1ddb.PNG">

스크린샷을 모르는게 아니라 windows installer 설치중이라 못찍은거에요 ㅋㅋㅋㅋㅋ
설치 되어있는데 왜 안되지;;

**Comment by GKO95** [comment]
![image](https://user-images.githubusercontent.com/44629526/93659832-72fc8400-fa84-11ea-92aa-1876b0cfc810.png)
ARM으로 설정하지 말고 x64나 x84로 설정해 봐.

**Comment by fora22** [comment]
ㄴㄴ 안됩니당;;

**Comment by fora22** [comment]
![image](https://user-images.githubusercontent.com/48875566/93659908-e2727380-fa84-11ea-9636-5cf419da9c05.png)
<br> 
머지 갑자기 됩니당;; 된거 맞죠 이거?

**Comment by GKO95** [comment]
![image](https://user-images.githubusercontent.com/44629526/93659909-e43c3700-fa84-11ea-9b86-29d0447b29be.png)
그럼 NuGet에서 설치된 것을 확인해 봐. 그리고 한 번 프로젝트 Rebuild도 해 보고.

**Comment by fora22** [comment]
이미 해봄욬ㅋㅋㅋㅋㅋㅋㅋㅋ VS도 재설치했는데...후...암튼 일단 해결됐으니..!
